#!/usr/bin/env python3
"""
Taiwan Invoice Skill - 持久化模式
將發票配置保存為 MASTER.md，供 AI 助手持續參考

用法:
    python persist.py init ECPay           # 初始化 ECPay 配置
    python persist.py init SmilePay        # 初始化 SmilePay 配置
    python persist.py show                 # 顯示當前配置
    python persist.py update --key xxx     # 更新配置
"""

import os
import sys
import argparse
from datetime import datetime
from typing import Dict, Any, Optional

# 取得 data 目錄路徑
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), 'data')

# 預設配置目錄
DEFAULT_CONFIG_DIR = 'invoice-config'
MASTER_FILENAME = 'MASTER.md'

# 服務商配置模板
PROVIDER_CONFIGS = {
    'ECPay': {
        'display_name': '綠界科技',
        'auth_method': 'AES-128-CBC',
        'test_url': 'https://einvoice-stage.ecpay.com.tw',
        'prod_url': 'https://einvoice.ecpay.com.tw',
        'test_merchant_id': '2000132',
        'test_hash_key': 'ejCk326UnaZWKisg',
        'test_hash_iv': 'q9jcZX8Ib9LM8wYk',
        'endpoints': {
            'issue_b2c': '/B2CInvoice/Issue',
            'issue_b2b': '/B2BInvoice/Issue',
            'void': '/Invoice/IssueInvalid',
            'allowance': '/Invoice/AllowanceByCollegiate',
            'print': '/Invoice/Print',
        },
        'encryption': 'URL Encode → AES-128-CBC → Base64',
    },
    'SmilePay': {
        'display_name': '速買配',
        'auth_method': 'Verify_key',
        'test_url': 'https://ssl.smse.com.tw/api_test',
        'prod_url': 'https://ssl.smse.com.tw/api',
        'test_merchant_id': 'SEI1000034',
        'test_hash_key': '9D73935693EE0237FABA6AB744E48661',
        'test_hash_iv': '',
        'endpoints': {
            'issue': '/SPEinvoice_Storage.asp',
            'void': '/SPEinvoice_Invalid.asp',
            'allowance': '/SPEinvoice_AllowanceByCollegiate.asp',
            'print': '/SPEinvoice_Print_Single.asp',
        },
        'encryption': 'URL Parameters + Verify_key',
    },
    'Amego': {
        'display_name': '光貿科技',
        'auth_method': 'MD5 Signature',
        'test_url': 'https://invoice-api.amego.tw',
        'prod_url': 'https://invoice-api.amego.tw',
        'test_merchant_id': '12345678',
        'test_hash_key': 'sHeq7t8G1wiQvhAuIM27',
        'test_hash_iv': '',
        'endpoints': {
            'issue': '/api/invoice/issue',
            'void': '/api/invoice/void',
            'allowance': '/api/invoice/allowance',
            'print': '/api/invoice/print',
        },
        'encryption': 'JSON + MD5(data + time + appKey)',
    },
}


def generate_master_md(provider: str, project_name: str = '', custom_config: Optional[Dict] = None) -> str:
    """
    生成 MASTER.md 內容
    """
    if provider not in PROVIDER_CONFIGS:
        raise ValueError(f"Unknown provider: {provider}")

    config = PROVIDER_CONFIGS[provider].copy()
    if custom_config:
        config.update(custom_config)

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    content = f"""# Taiwan Invoice - 專案配置

> 此檔案為 AI 助手的持久化配置，請勿手動刪除

## 基本資訊

| 項目 | 值 |
|------|-----|
| **專案名稱** | {project_name or '未命名專案'} |
| **加值中心** | {config['display_name']} ({provider}) |
| **建立時間** | {now} |
| **環境** | 測試環境 |

---

## 服務商配置

### {config['display_name']} ({provider})

**認證方式**: {config['auth_method']}

**API 端點**:
- 測試: `{config['test_url']}`
- 正式: `{config['prod_url']}`

**測試憑證**:
```
MerchantID: {config['test_merchant_id']}
HashKey: {config['test_hash_key']}
HashIV: {config['test_hash_iv'] or 'N/A'}
```

**加密流程**:
```
{config['encryption']}
```

---

## API 端點

| 操作 | 端點 |
|------|------|
"""

    for op, endpoint in config['endpoints'].items():
        content += f"| {op} | `{endpoint}` |\n"

    content += f"""
---

## 發票類型設定

### B2C (二聯式)

- 金額: **含稅價**
- BuyerIdentifier: `0000000000`
- TaxAmount: `0`
- 可使用載具/捐贈

### B2B (三聯式)

- 金額: **未稅價**
- 需填寫統編 (8碼)
- 需計算稅額: `TaxAmount = round(Total - Total/1.05)`
- **不可**使用載具/捐贈

---

## 環境變數建議

```env
# {config['display_name']} 配置
INVOICE_PROVIDER={provider}
INVOICE_MERCHANT_ID=
INVOICE_HASH_KEY=
INVOICE_HASH_IV=
INVOICE_ENV=test
```

---

## 開發檢查清單

- [ ] 設定環境變數
- [ ] 實作加密/解密函數
- [ ] 建立 InvoiceService 介面
- [ ] 實作 {provider}InvoiceService
- [ ] 處理 B2C/B2B 金額計算差異
- [ ] 儲存 invoiceProvider 和 randomNumber
- [ ] 實作錯誤處理與 logger
- [ ] 測試環境驗證

---

## 注意事項

1. **randomNumber**: 開立成功後務必儲存，列印時需要
2. **invoiceProvider**: 開立時儲存使用的服務商，列印時使用
3. **時間戳記**: {"ECPay 需在 10 分鐘內" if provider == 'ECPay' else "Amego 需在 60 秒內" if provider == 'Amego' else "注意伺服器時間"}
4. **載具與捐贈**: 互斥，不可同時設定

---

*Generated by Taiwan Invoice Skill v2.3.0*
"""

    return content


def init_config(provider: str, target_dir: str, project_name: str = '', force: bool = False) -> str:
    """
    初始化配置
    """
    config_dir = os.path.join(target_dir, DEFAULT_CONFIG_DIR)
    master_path = os.path.join(config_dir, MASTER_FILENAME)

    # 檢查是否已存在
    if os.path.exists(master_path) and not force:
        raise FileExistsError(f"Config already exists: {master_path}. Use --force to overwrite.")

    # 建立目錄
    os.makedirs(config_dir, exist_ok=True)

    # 生成內容
    content = generate_master_md(provider, project_name)

    # 寫入檔案
    with open(master_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return master_path


def show_config(target_dir: str) -> Optional[str]:
    """
    顯示當前配置
    """
    master_path = os.path.join(target_dir, DEFAULT_CONFIG_DIR, MASTER_FILENAME)

    if not os.path.exists(master_path):
        return None

    with open(master_path, 'r', encoding='utf-8') as f:
        return f.read()


def format_ascii_box(title: str, content: str, width: int = 70) -> str:
    """
    格式化 ASCII Box
    """
    lines = []
    lines.append('╔' + '═' * (width - 2) + '╗')
    lines.append('║' + f' {title}'.center(width - 2) + '║')
    lines.append('╠' + '═' * (width - 2) + '╣')

    for line in content.split('\n'):
        if len(line) > width - 4:
            line = line[:width - 7] + '...'
        lines.append('║' + ' ' + line.ljust(width - 4) + ' ' + '║')

    lines.append('╚' + '═' * (width - 2) + '╝')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Taiwan Invoice - 持久化配置工具',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python persist.py init ECPay                    # 初始化 ECPay 配置
  python persist.py init SmilePay -p "MyProject"  # 指定專案名稱
  python persist.py show                          # 顯示當前配置
  python persist.py init Amego --force            # 強制覆蓋
        """
    )

    subparsers = parser.add_subparsers(dest='command', help='Commands')

    # init 命令
    init_parser = subparsers.add_parser('init', help='Initialize configuration')
    init_parser.add_argument('provider', choices=['ECPay', 'SmilePay', 'Amego'],
                             help='Invoice provider')
    init_parser.add_argument('-p', '--project', default='',
                             help='Project name')
    init_parser.add_argument('-d', '--dir', default='.',
                             help='Target directory (default: current)')
    init_parser.add_argument('-f', '--force', action='store_true',
                             help='Force overwrite existing config')

    # show 命令
    show_parser = subparsers.add_parser('show', help='Show current configuration')
    show_parser.add_argument('-d', '--dir', default='.',
                             help='Target directory (default: current)')

    # list 命令
    list_parser = subparsers.add_parser('list', help='List available providers')

    args = parser.parse_args()

    if args.command == 'init':
        try:
            path = init_config(args.provider, args.dir, args.project, args.force)
            print(format_ascii_box(
                '✓ Configuration Initialized',
                f"Provider: {args.provider}\nPath: {path}\n\nNext: Set your credentials in the MASTER.md file"
            ))
        except FileExistsError as e:
            print(f"Error: {e}")
            sys.exit(1)
        except ValueError as e:
            print(f"Error: {e}")
            sys.exit(1)

    elif args.command == 'show':
        content = show_config(args.dir)
        if content:
            print(content)
        else:
            print("No configuration found. Run 'python persist.py init <provider>' to create one.")

    elif args.command == 'list':
        print("\nAvailable Providers:")
        print("=" * 50)
        for provider, config in PROVIDER_CONFIGS.items():
            print(f"\n  {provider}")
            print(f"    {config['display_name']}")
            print(f"    Auth: {config['auth_method']}")
        print()

    else:
        parser.print_help()


if __name__ == '__main__':
    main()
